# Generated by Django 5.0.4 on 2024-04-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
        migrations.DeleteModel(
            name='VideoTag',
        ),
    ]
