# Generated by Django 5.0.4 on 2024-04-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoservice', '0004_alter_comments_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
        migrations.DeleteModel(
            name='VideoTag',
        ),
    ]
