# Generated by Django 5.0.4 on 2024-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoservice', '0006_videotag_video_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
