# Generated by Django 5.0.4 on 2024-04-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_follows_profile_subscribers'),
        ('videoservice', '0010_remove_video_playlist_video_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
