# Generated by Django 5.0.4 on 2024-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoservice', '0011_video_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
