# Generated by Django 5.0.4 on 2024-04-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoservice', '0012_video_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subscribers',
        ),
    ]
