# Generated by Django 5.0.4 on 2024-04-29 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_follows_profile_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yes',
            field=models.ManyToManyField(blank=True, related_name='videoservice.Video.subscribers+', to=settings.AUTH_USER_MODEL),
        ),
    ]
