# Generated by Django 5.0.4 on 2024-04-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='yes',
        ),
    ]
