# Generated by Django 5.0.4 on 2024-05-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
    ]
